'''Representation of graphs given by user'''

import re
from . import graph_functions as gf
from collections import defaultdict

class Graph(object):
    def __init__(self, nodes: set, edges: set, var_map: dict, paths: list, output_graph=[], 
                    table = []) -> None:
        '''
        Initialize values and create function maps
        
        Variables
        self.nodes: set of CypherType objects representing the nodes in the graph
        self.edges: set of CypherType objects representing the edges in the graph
        self.vars: dictionary mapping variable names to their corresponding index in the paths
        self.paths: list of tuples of CypherType objects representing a collection of concrete paths
        self.output_graph: list of CypherType objects representing the result of the query. Left empty until call to return
        self.table: values in table shape; For example, table as below is written as [[1, 4], [2, 5], [3, 6]]
        ----------
        1 | 2 | 3
        ----------
        4 | 5 | 6
        ----------

        Maps
        self.binary_operations: dictionary mapping function names to appropriate binary functions
        self.aggregators: dictionary mapping aggregation function names to appropriate aggregating functions
        '''

        self.nodes = nodes 
        self.edges = edges
        self.vars = var_map
        self.paths = paths
        self.output_graph = output_graph
        self.table = table

        self.binary_operations = {
            'add': gf.Addition(),
            'sub': gf.Subtraction(),
            'div': gf.Division(),
            'mul': gf.Multiplication(),
            'equal': lambda a,b: a == b,
            'ne': lambda a,b: a != b,
            'lt': lambda a,b: a < b,
            'lte': lambda a,b: a <= b,
            'and': lambda a,b: [(x and y) for x,y in zip(a,b)], 
            'or': lambda a,b: [(x or y) for x,y in zip(a,b)],
        }

        self.aggregators = {
            'COUNT': gf.Count(),
            'SUM': gf.Sum(),
            'MAX': gf.Max(),
            'MIN': gf.Min(),
            'AVG': gf.Avg()
        }
    

    def __eq__(self, other):
        '''Compare the graphs based on their paths and their output graphs'''
        return create_bag(self.paths) == create_bag(other.paths) and compare_table(self.table, self.output_graph, other.table, other.output_graph)
        # return create_bag(self.paths) == create_bag(other.paths) and create_bag(self.output_graph) == create_bag(other.output_graph)
  
    def __hash__(self):
        '''Hash based on the length of paths and length of output graph'''
        return hash(len(self.paths)) ^ hash(len(self.output_graph))
    
    def match(self, path_pattern: str):
        '''
        Match corresponding concrete paths that match the given path_pattern

        Paramaters
        path_pattern: string generated by CreatePathPattern in semantics_cypher.py that describes path to match

        Return
        A new Graph object with identical nodes and edges, an updated variable map, and updated concrete paths

        Failure results in a Graph object returned with empty variable map and paths
        '''

        path = [tuple(x.strip('()').split(',')) for x in path_pattern.split(':')]
        vars, paths = self.vars.copy(), self.paths.copy()
        for i in range(len(path)):
            for j in range(i, len(path)):
                if path[i][0] == path[j][0] and path[i][1] != path[j][1]:
                    return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])
                
        if len(path) == 1:
            (var_name, label) = path[0]

            # new variable means we have to cartesian with all nodes of that label
            if var_name not in vars:
                search_nodes = [x for x in self.nodes if label == x.get_property('label')]
                
                if search_nodes == []:
                    return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])

                new_paths = [(node,) for node in search_nodes] if len(paths) == 0 else [x + (node,) for x in self.paths for node in search_nodes]
                vars[var_name] = (len(new_paths[0]) - 1, label) # (idx of the variable on the path?, label)
                return Graph(nodes=self.nodes, edges=self.edges, var_map=vars, paths=new_paths)
            else:
                return Graph(nodes=self.nodes, edges=self.edges, var_map=vars, paths=paths)

        # if the pattern is longer than 1 node, then delegate to the create_table function to build out matching paths
        (paths, vars) = self.create_table('', path, paths, vars)
        return Graph(nodes=self.nodes, edges=self.edges, var_map=vars, paths=paths)
    
    def matchr(self, path_pattern):
        '''
        Recursive match corresponds to all of the matches after the first

        Parameters
        path_pattern: string generated by CreatePathPattern in semantics_cypher.py that describes path to match

        Return
        A new Graph object with identical nodes and edges, an updated variable map, and updated concrete paths

        Failure results in a Graph object returned with empty variable map and paths
        '''

        path = [tuple(x.strip('()').split(',')) for x in path_pattern.split(':')]

        if len(self.paths) == 0:
            return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])

        # ensure that at variables in new path are not completely disjoint with existing variables
        new_path_vars, existing_vars = set([x[0] for x in path]), set(self.vars.keys())

        if new_path_vars.isdisjoint(existing_vars):
            return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])

        # make sure labels agree for shared variables 
        for var in path:
            if var[0] in self.vars and var[1] != self.vars[var[0]][1]:
                return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])

        # generate tables for each of the match clauses
        previous_path, previous_vars = self.paths, self.vars
        new_paths, new_vars = self.create_table('', path, [], {})

        shared_variables = new_path_vars.intersection(previous_vars)
        different_variables = new_path_vars - existing_vars
       
        # cartesian the new and old paths, filtering on equality of shared variables
        final_paths = []
        for old_path in previous_path:
            for new_path in new_paths:
                valid_pair = True

                # if not equal on all shared variables, then we don't include that path
                for shared_variable in shared_variables:
                    (new_path_index, _), (old_path_index, _) = new_vars[shared_variable], previous_vars[shared_variable]

                    if old_path[old_path_index] != new_path[new_path_index]:
                        valid_pair = False
                        break
            
                # if they agree on all shared variables, then we merge our var_map and create extended paths
                if valid_pair:
                    temp = old_path
                    for different_var in different_variables:
                        new_path_index, new_path_label = new_vars[different_var]
                        temp = temp + (new_path[new_path_index],)
                        previous_vars[different_var] = len(temp) - 1, new_path_label

                    final_paths.append(temp)

        return Graph(nodes=self.nodes, edges=self.edges, var_map=previous_vars, paths=final_paths)
    
    def filter(self, predicate):
        '''
        Filters existing paths based on the predicate given

        Paramaters
        predicate: string generated by combination of operations definied in semantics_cypher.py

        Return
        A new graph object with the filtered paths

        Failure results in a Graph object returned with empty variable map and paths
        '''
        
        try:
            parsed = self.parse_expression(predicate)
        except ValueError:
            return Graph(nodes=self.nodes, edges=self.edges, var_map=self.vars, paths=[])
        
        # attempt to construct a boolean bit_vector representing whether each concrete path satisfies the predicate 
        try:
            bit_vector = self.evaluate_expression_on_paths(parsed, self.paths)
        except ValueError:
            return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])
        
        # filter out paths that do no satisfy predicate
        new_paths = [path for path, pred in zip(self.paths, bit_vector) if pred]
        return Graph(nodes=self.nodes, edges=self.edges, var_map=self.vars, paths=new_paths)
    
    def ret(self, list_of_properties):
        '''
        Return graph function that takes current paths and returns given properties

        Parameteres
        list_of_properties: string genereated by the CreateExpressionList function in semantics_cypher.py

        Return
        A new graph object with empty paths and output_graph representing the output of the query

        Failure results in a Graph object returned with empty paths and output_graph        
        '''
        
        properties = list_of_properties.split(':')
        try:
            parsed_properties = [self.parse_expression(p) for p in properties]
        except:
            return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])
            
         # duplicate properties causes it to fail
         # TODO: May need to change this, no need to decide failure in this case
        if len(parsed_properties) != len(set(parsed_properties)):
            return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[])
        
        
        output_graph, table = self.construct_return_graph(parsed_properties)
        return Graph(nodes=self.nodes, edges=self.edges, var_map={}, paths=[], output_graph=output_graph, table=table)
    
    # GRAPH UTIL FUNCTIONS
    def create_table(self, last_node_var, pattern_list, paths, vars):
        '''
        Helper function called in match and matchr that recursively builds out list of matching paths

        Parameters
        last_node_var: string given as the last variable used in the path. Default is '' for the first call
        pattern_list: list of parsed node/edge patterns to match
        paths: list of CypherType tuples representing already matches concrete paths
        vars: dictionary mapping variables names to indices in the path

        Return
        (paths, vars) tuple of updated paths and variable map
        '''
        
        # base case of pattern exhausted
        if len(pattern_list) == 0:
            return paths, vars

        # initial call has last_node_var as '' and we need to build the first node
        if last_node_var == '':
            (var_name, label) = pattern_list[0]

            if var_name not in vars:
                search_nodes = [x for x in self.nodes if label == x.get_property('label')]
                paths = [(node,) for node in search_nodes]
                vars[var_name] = (0, label)

            return self.create_table(var_name, pattern_list[1:], paths, vars)
        
        # no concrete paths match the pattern so return empty
        if len(paths) == 0:
            return (paths, {})
        
        # unpack our next edge and node from the pattern
        (edge_var, edge_type, edge_direction), (node_var, node_label) = pattern_list[0], pattern_list[1]
        
        # each edge must be distinct so if we have already used edge_var then it cannot be used again. Exit here
        if edge_var in vars:
            return self.create_table(node_var, pattern_list, [], vars)
        
        new_paths = []

        # handle loops
        if last_node_var == node_var:
            search_edges = [x for x in self.edges if edge_type == x.get_property('label')]
            node_index, _ = vars[last_node_var]

            for path in paths:
                node = path[node_index]
                for edge in search_edges:
                    if edge.get_property('start') == node.get_property('element_id') and edge.get_property('end') == node.get_property('element_id') and edge not in path:
                        new_paths.append(path + (edge,))
                        vars[edge_var] = (len(path), edge_type)
        else:
            search_edges = [x for x in self.edges if x.get_property('label') == edge_type]
            
            if node_var not in vars:
                search_nodes = [node for node in self.nodes if node_label == node.get_property('label')]
                
                last_node_index, _ = vars[last_node_var]
                for path in paths:
                    last_node = path[last_node_index]
                    for other_node in search_nodes:
                        for edge in search_edges:
                            # generalizing in this condition based off of which way the direction is
                            if (edge_direction == '<-' and edge.get_property('end') == last_node.get_property('element_id') and edge.get_property('start') == other_node.get_property('element_id') and edge not in path) or\
                                (edge_direction == '->' and edge.get_property('start') == last_node.get_property('element_id') and edge.get_property('end') == other_node.get_property('element_id') and edge not in path):
                                    new_paths.append(path + (edge,other_node))
                                    vars[edge_var] = (len(path), edge_type)
                                    vars[node_var] = (len(path) + 1, node_label)
            else:
                # node variable is bound so we only have to check edges that connect nodes already bound in our pathseBer
                (start_index, _), (end_index, _) = vars[node_var], vars[last_node_var]

                # if our edge is going left to right then we need to change our start/end nodes, so just swap the indices
                if edge_direction == '->':
                    start_index,end_index = end_index,start_index

                for path in paths:
                    start_node, end_node = path[start_index], path[end_index]
                    for edge in search_edges:
                        if edge.get_property('start') == start_node.get_property('element_id') and edge.get_property('end') == end_node.get_property('element_id') and edge not in path:
                            new_paths.append(path + (edge, start_node))
                            vars[edge_var] = (len(path), edge_type)
        return self.create_table(node_var, pattern_list[2:], new_paths, vars)
    
    
    def construct_return_graph(self, properties):
        '''
        Based on the table constructed through matches/filters construct a resulting output graph of all expressions,
        and a table including the correspondence of the expressions.

        Parameters
        properties: string generated by CreateExpressionList in cypher_semantics that represnts what to return

        Return
        List of CypherType objects representing the output graph
        '''
        if len(self.paths) == 0:
            return ([], [])

        # TODO: Rewrite the group by function here
        
        groups = {('all',): self.paths}
        aggregators = []


        # Group by case with aggregations
        for property in properties:
            if self.expression_contains_aggregation(property):
                aggregators.append(property)
            else:
                # this property is the grouping key; groups will be iteratively grouped by all grouping keys 
                try:
                    groups = self.split_groups(groups, property)
                except ValueError:
                    return ([], [])         
        
        # compute the values of the aggregating expressions
        output_graph = []
        if len(aggregators) > 0:
            if len(aggregators) != len(set(aggregators)):
                return ([], [])
            
            for expression in aggregators:
                agg_values = []
                
                for group in groups.values():
                    # this will create whatever values we want I think
                    try:
                        # TODO: For certain data group 'group', 'group' is a list of paths, here grouping keys are not grouped
                        for result in self.evaluate_expression_on_paths(expression, group):
                            key = self.create_key_from_expression(expression)
                            key['values'] = create_bag([result])
                            output_graph.append(CypherType(key))
                    except ValueError:
                        return ([], [])
                    
                    agg_values.append(result)


            # compute the values from the grouping keys that we need to return, grouping on variables
            for x in groups.keys():
                # TODO: Grouping keys are not 'grouped'
                variable_property_mapping = {}
                x = x[1:]
                for grouping_value in x:
                    value, metadata = grouping_value

                    # when return the complete node or edge
                    if metadata[0] == 'variable':
                        var = metadata[1]
                        is_edge = value.get_property('start') is not None and value.get_property('end') is not None

                        if var in variable_property_mapping:
                            if is_edge:
                                variable_property_mapping[var].add((value.get_property('start'), 'start'))
                                variable_property_mapping[var].add((value.get_property('end'), 'end'))

                            variable_property_mapping[var].add((value.get_property('element_id'), 'element_id'))
                        else:
                            variable_property_mapping[var] = set([(value.get_property('element_id'), 'element_id')])

                            if is_edge:
                                variable_property_mapping[var].add((value.get_property('start'), 'start'))
                                variable_property_mapping[var].add((value.get_property('end'), 'end'))
                    elif metadata[0] == 'property':
                        _, var, prop = metadata

                        if var in variable_property_mapping:
                            variable_property_mapping[var].add((value, prop))
                        else:
                            variable_property_mapping[var] = set([(value, prop)])
                    else:
                        key = self.create_key_from_expression(metadata)
                        key['values'] = create_bag(self.evaluate_expression_on_paths(prop, self.paths))
                        output_graph.append(CypherType(key))

                for var, properties in variable_property_mapping.items():
                    _, label = self.vars[var]

                    val = {'label': label}
                    for prop in properties:
                        value, prop_name = prop

                        val[prop_name] = value

                    output_graph.append(CypherType(val))
                output_graph = list(set(output_graph))

        else:
            # When return clause only include non-aggregations

            # create a map between variables and the properties to return for each
            var_to_property_map = {var_name: set() for var_name in self.vars}
            # there are no aggregators, so we just construct our graph based off of self.paths, keeping in mind that we are mapping by concrete node
            for prop in properties:
                if prop[0] == 'variable':
                    var_name = prop[1]
                    var_to_property_map[var_name].add('element_id')

                elif prop[0] == 'property':
                    var_name, prop_name = prop[1], prop[2]
                    var_to_property_map[var_name].add(prop_name)

            # now we have our mappings for each of them we need to go collect our var -> concrete node mappings so we know what to apply to
            var_to_concrete_nodes_map = {var_name: list() for var_name in self.vars}

            for prop in properties:
                if prop[0] == 'variable' or prop[0] == 'property':
                    var_name = prop[1]
                    
                    for path in self.paths:
                        var_to_concrete_nodes_map[var_name].append(path[self.vars[var_name][0]])
                # elif prop[0] == 'constant':  # What is this for??
                #     output_graph.append(CypherType({"type": "constant", "value": prop[1]}))
                # else:
                    # it is some sort of operation
                    # TODO: Fix this as well, this is for a.age+b.age case
                    # for value in self.evaluate_expression_on_paths(prop, self.paths):
                    #     key = self.create_key_from_expression(prop)
                    #     key['values'] = create_bag([value])
                    #     output_graph.append(CypherType(key))
                    # pass

            # now, we just need to project our variables, keeping a grouping for each concrete node as well
            concrete_nodes_cypher_type_map = {}

            output_graph = []
            table = []
            object_id = 1
            for var, concrete_obj_list in var_to_concrete_nodes_map.items():
                # now should be 
                property_set = var_to_property_map[var]
                # for each property, there should be a column for it
                for property in property_set:
                    column = []

                    for concrete_obj in concrete_obj_list:
                        # full_value = {'label': concrete_obj.get_property('label')}
                        id = concrete_obj.get_property('element_id')
                        if property == "element_id":
                            propertyT = "full"
                        else:
                            propertyT = property

                        is_edge = concrete_obj.get_property('start') is not None and concrete_obj.get_property('end') is not None
                        if is_edge:
                            object = CypherOutputType(property=propertyT, inputItems=["e"+str(id)], operator='', lhs=None, rhs=None)
                        else:
                            object = CypherOutputType(property=propertyT, inputItems=["n"+str(id)], operator='', lhs=None, rhs=None)
                        
                        output_graph.append(object)
                        column.append(object_id)

                        object_id += 1
                    
                    table.append(column)

                    # for property in property_set:
                        # full_value[property] = concrete_obj.get_property(property)
                        # if is_edge and property == 'element_id':
                        #     # if it's and edge we are returning our start and end as well
                        #     full_value['start'] = concrete_obj.get_property('start')
                        #     full_value['end'] = concrete_obj.get_property('end')
                    # if concrete_obj in concrete_nodes_cypher_type_map:
                    #     concrete_nodes_cypher_type_map[concrete_obj].append(CypherType(full_value))
                    # else:
                    #     concrete_nodes_cypher_type_map[concrete_obj] = [CypherType(full_value)]
            # for objects in concrete_nodes_cypher_type_map.values():
            #     entire_rep = self.merge_cypher_types(objects)
            #     output_graph.append(entire_rep)
          
        return (output_graph, table)

    def merge_cypher_types(self, list_of_cypher_types):
        '''
        Helper function to merge properties across the same concrete nodes
        '''
        if len(list_of_cypher_types) == 1:
            return list_of_cypher_types[0]
        
        combined_value = {}
        for val in list_of_cypher_types:
            for key,value in val.properties.items():
                if key not in combined_value:
                    combined_value[key] = value

        return CypherType(combined_value)

    def create_key_from_expression(self, expression):
        '''
        Given an expression create a key that will be used in the output graph
        '''

        if expression[0] == 'constant':
            return expression[1]
        elif expression[0] == 'property':
            _, var_name, prop = expression

            return f'{self.vars[var_name][1]}.{prop}'
        elif expression[0] == 'variable':
            var_name = expression[1]
            label = self.vars[var_name][1]
            return f'{label}.complete'
        
        if expression[0] == 'aggregator':
            # then we are unary and can just construct the one
            return {'operation': expression[1], 'arguments': [self.create_key_from_expression(expression[2])]}
        elif expression[0] == 'binary_operation':
            return {'operation': expression[1], 'arguments': [self.create_key_from_expression(expression[2]), self.create_key_from_expression(expression[3])]}

    def expression_contains_aggregation(self, expression):
        '''
        Helper function to determine whether grouping keys are needed
        '''
        
        if expression[0] == 'property' or expression[0] == 'constant' or expression[0] == 'variable':
            return False
        
        if expression[0] == 'aggregator':
            return True
        
        # else it is a binary operation
        return self.expression_contains_aggregation(expression[2]) or self.expression_contains_aggregation(expression[3])
 
    def split_groups(self, groups, grouper):
        '''
        Helper function that splits our groups further based on the given 'grouper'

        Parameters
        groups: dictionary grouping values to the paths that have it
        grouper: tuple representing an expression that should be evaluated and used for grouping

        Return
        New dictionary with further grouping
        '''

        values = self.evaluate_expression_on_paths(grouper, self.paths)

        # create pairs of values and corresponding paths
        values = [(x,y) for x,y in zip(values, self.paths)]

        new_groups = {}
        for key, value in groups.items():
            val = self.evaluate_expression_on_paths(grouper, value)

            for new_value, path in zip(val, value):
                combined_tuple = (key,) + ((new_value, grouper),) if len(key) == 1 else key + ((new_value, grouper),)

                if combined_tuple in new_groups:
                    new_groups[combined_tuple].append(path)
                else:
                    new_groups[combined_tuple] = [path]

        return new_groups

    # PARSING UTIL FUNCTIONS
    def parse_expression(self, statement):
        '''
        Given an expression this parses it into more manageable form with underlying metadata about it's elements

        Parameters
        statement: string representing an expression created by various functions in semantics_cypher.py

        Return
        Tuple representing the type, value, and any arguments if applicable        
        '''

        # matches functions of the form 'func_name(arg1, arg2)
        function_pattern = re.compile(r'(\w+)\((.*)\)')
        match = function_pattern.match(statement)
        
        if match:
            func_name = match.group(1)
            split_args = self.split_function_operands(match.group(2))
            if len(split_args) == 2:
                arg1 = self.parse_expression(split_args[0])
                arg2 = self.parse_expression(split_args[1])
                return ('binary_operation', func_name, arg1, arg2)
            elif len(split_args) == 1:
                arg1 = self.parse_expression(split_args[0])
                return ('aggregator', func_name, arg1)              
        
        # then it is a property
        if '.' in statement:
            name, prop = statement.split('.', 1)

            if name not in self.vars:
                raise ValueError
            
            return ('property',  name.strip(), prop.strip())

        # if we have used it as a variable, then it is such, else it is a constant
        if statement in self.vars:
            return ('variable', statement)
        
        # if is tuple representation then treat it as such
        if statement[0] == '(' and statement[-1] == ')':
            return ('constant', tuple(statement.strip('(),').split(',')))

        try:
            return ('constant', float(statement)) if statement[0] != '0' else ('constant', statement)
        except:
            return ('constant', statement)
            
    def split_function_operands(self, args):
        '''
        Helper function to split the two arguments to a function based of placement of paranthesess
        
        Parameters
        args: string representing arguments to a function

        Return
        List of the form [arg1, arg2]
        '''

        depth = 0
        operands = []
        current_operand = []
        
        for char in args:
            if char == ',' and depth == 0:
                operands.append(''.join(current_operand))
                current_operand = []
            else:
                current_operand.append(char)
                if char == '(':
                    depth += 1
                elif char  == ')':
                    depth -= 1
                    
        operands.append(''.join(current_operand))

        return operands
        
    def evaluate_expression_on_paths(self, expression, paths):
        '''
        Helper function that takes an expression and evaluates it on the list of given paths

        Parameters
        expression: tuple representing the expression to evaluate
        paths: list of paths to evaluate the expression on

        Return
        List of values that result from evaluation        
        '''
        if expression[0] == 'constant':
            return [expression[1] for _ in range(len(paths))]
        
        elif expression[0] == 'variable':
            index, _ = self.vars[expression[1]]
            return [path[index] for path in paths]
        
        elif expression[0] == 'property':
            var_name, prop = expression[1], expression[2]
           
            properties = []
            index,_ = self.vars[var_name]
            for path in paths:
                obj = path[index]
                obj_prop = obj.get_property(prop)
                if obj_prop is None:
                    raise ValueError

                properties.append(obj_prop)
            return properties
        
        elif expression[0] == 'binary_operation':
            func_name, arg1, arg2 = expression[1], self.evaluate_expression_on_paths(expression[2], paths), self.evaluate_expression_on_paths(expression[3], paths)
            
            results = []
            if func_name in ['and', 'or']:
                return self.binary_operations[func_name](arg1, arg2)
            
            for x,y in zip(arg1, arg2):
                if func_name in ['sub', 'add', 'div', 'mul']:
                    results.append(self.binary_operations[func_name].evaluate([x,y]))
                else:
                    results.append(self.binary_operations[func_name](x, y))

            return results
        
        elif expression[0] == 'aggregator':
            func_name = expression[1]

            argument = self.evaluate_expression_on_paths(expression[2], paths)
            result = self.aggregators[func_name].evaluate(argument)

            if isinstance(result, CypherType):
                return [result]
            
            return [round(result, 5)]

def compare_helper(a: list, b:list, output_graph_a: list, output_graph_b: list):
    equal = True
    for obj_a in a:
        canFind = False
        for obj_b in b:
            # index of objects in table starts from 1
            if output_graph_a[obj_a-1] == output_graph_b[obj_b-1]:
                canFind = True
                break
        if canFind == False:
            equal = False
            break
    return equal
    
def get_rows(table: list):
    transposed = []
    if len(table) > 0:
        transposed_table = defaultdict(list)
        for col in table:
            for row_id in range(len(col)):
                transposed_table[row_id].append(col[row_id])
        for row_id in range(len(table[0])):
            transposed.append(transposed_table[row_id])
    return transposed

def compare_table(table_a: list, output_graph_a: list, table_b: list, output_graph_b: list):
    '''
    Compare output of queries(in table shapes)
    table_a: current enumerated result
    table_b: target table
    output_graph_a: current enumerated output graph
    output_graph_b: target output graph
    
    Each table should be formatted as [[CypherOutputType]]
    '''
    equal = True
    # compare columns in table_a and table_b
    for col_a in table_a:
        canFind = False
        for col_b in table_b:
            if compare_helper(col_a, col_b, output_graph_a, output_graph_b):
                canFind = True
                break
        if canFind == False:
            equal = False
            return equal
    for col_b in table_b:
        canFind = False
        for col_a in table_a:
            if compare_helper(col_a, col_b, output_graph_a, output_graph_b):
                canFind = True
                break
        if canFind == False:
            equal = False
            return equal

    # Get all the rows from table_a and table_b
    rows_a = get_rows(table_a)
    rows_b = get_rows(table_b)
    # compare rows in rows_a and rows_b
    for row_a in rows_a:
        canFind = False
        for row_b in rows_b:
            if compare_helper(row_a, row_b, output_graph_a, output_graph_b):
                canFind = True
                break
        if canFind == False:
            equal = False
            return equal
    for row_b in rows_b:
        canFind = False
        for row_a in rows_a:
            if compare_helper(row_a, row_b, output_graph_a, output_graph_b):
                canFind = True
                break
        if canFind == False:
            equal = False
            return equal

    return equal

    
def create_bag(values):
    '''
    Create a multiset from a list of values
    '''

    bag = {}
    for v in values:
        if v in bag:
            bag[v] += 1
        else:
            bag[v] = 1

    return bag

class CypherType():
    '''
    Represents an object in our input graphs
    '''

    def __init__(self, properties: dict) -> None:
        self.properties = properties
    
    def get_property(self, property):
        if property in self.properties:
            return self.properties[property]
        
        return None
    
    def to_dict(self):
        return self.properties
       
    def __hash__(self):
        return len(self.properties)
    
    def __eq__(self, other):
        return self.properties == other.properties
    
class CypherOutputType():
    '''
    Represents an object in our output graphs
    '''

    def __init__(self, property: str, operator: str, inputItems: list, lhs, rhs) -> None:
        self.property = property
        self.operator = operator
        self.inputItems = inputItems
        self.lhs = lhs
        self.rhs = rhs
    
    def to_dict(self):
        raise NotImplementedError 
       
    def __hash__(self):
        raise NotImplementedError 
    
    def __eq__(self, other):
        if self.lhs == {}:
            self.lhs = None
        if self.rhs == {}:
            self.rhs = None
        if other.lhs == {}:
            other.lhs = None
        if other.rhs == {}:
            other.rhs = None
        if self.lhs is None and self.rhs is None and other.lhs is None and other.rhs is None:
            # No need to compare expression with +, -, *, /
            equal = True
            if self.operator != other.operator:
                equal = False
            if self.property != other.property:
                equal = False
            if dataCnt_helper(self.inputItems) != dataCnt_helper(other.inputItems):
                equal = False
            
        return equal 
 
def dataCnt_helper(datas: list):
    dataCnt = defaultdict(int)
    for data in datas:
        dataCnt[data] += 1
    return dataCnt